[project]
id = "puckle"
name = "puckle"
version = "0.0.1"

[components]
camera_pitch = { type = "F32", name = "Player Camera Pitch", description = "" }
camera_yaw = { type = "F32", name = "Player Camera Yaw", description = "" }
camera_zoom = { type = "F32", name = "Player Camera Zoom", description = "", attributes = ["Networked"]}
camera_mode = { type = "U32", name = "Camera Mode", description = "", attributes = ["Networked"]}

player_camera_ref = { type = "EntityId", name = "Player camera ref", description = "", attributes = [
    "Networked",
] }
world_ref = { type = "EntityId", name = "Voxel world ref", description = "" }
voxel_world = { type = { type = "Vec", element_type = "EntityId" }, name = "Voxel World", description = "" }
voxel = { type = "Empty", name = "Voxel", description = "" }
current_animation = { type = "String", name = "", description = "" }
jumping = { type = "Bool", name = "", description = "" }
jump_timer = { type = "F32", name = "", description = "" }

[messages.input]
name = "Input"
description = "The player's input"
[messages.input.fields]
left_click = { type = "Bool", name = "Left Click", description = "" }
w = { type = "Bool", name = "Up", description = "Whether the player is pressing the up key" }
s = { type = "Bool", name = "Down", description = "Whether the player is pressing the down key" }
a = { type = "Bool", name = "Left", description = "Whether the player is pressing the left key" }
d = { type = "Bool", name = "Right", description = "Whether the player is pressing the right key" }
jump = { type = "Bool", name = "Jump", description = "Whether the jump key changed since last frame" }

no_wasd = { type = "Bool", name = "Jump", description = "Whether the jump key changed since last frame" }
wasd_delta = { type = "Bool", name = "Jump", description = "Whether the jump key changed since last frame" }

camera_rotation = { type = "Vec2", name = "Camera Rotation", description = "The rotation (radians) to rotate the camera by" }
camera_zoom = { type = "F32", name = "Camera Zoom", description = "The amount to zoom the camera by" }
mouse_position = { type = "Vec2", name = "Mouse Position", description = "" }
ray_origin = { type = "Vec3" }
ray_dir = { type = "Vec3" }

[messages.camera_mode]
name = "CameraMode"
description = "Set the camera mode"
[messages.camera_mode.fields]
mode = { type = "U32", name = "The mode being set", description = "" }
camera_id = { type = "EntityId", name = "The id of the camera", description = "" }